## Dataset link: https://www.kaggle.com/c/house-prices-advanced-regression-techniques

In [1]:
import pandas as pd
import dtale

In [2]:
dataset = pd.read_csv("eda_train.csv")

In [3]:
dataset.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
dataset.shape

(1460, 81)

## EDA using Dtale

## Method 1

In [ ]:
dtale.show(dataset)

## Method 2

In [6]:
dtale.show(open_browser=True)

c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py:1711: FutureWarning:

The default value of regex will change from True to False in a future version.

Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

2021-11-11 12:56:13,922 - ERROR    - Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

2021-11-11 12:56:14,097 - ERROR    - Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

2021-11-11 12:56:15,232 - ERROR    - Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

2021-11-11 12:56:15,441 - ERROR    - Exception occurred while processing request: cannot assign without a target object
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 1627, in test_filter
    run_query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\query.py", line 62, in run_query
    df = df.query(
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4060, in query
    res = self.eval(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 806, in __init__
    self.terms = self.parse()
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 825, in parse
    return self._visitor.visit(self.expr)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\pandas\core\computation\expr.py", line 619, in visit_Assign
    raise ValueError("cannot assign without a target object")
ValueError: cannot assign without a target object

Exception occurred while processing request: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (81).
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 3257, in build_missingno_chart
    figure = msno.bar(df)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\missingno\missingno.py", line 266, in bar
    ax3.set_xticklabels(nullity_counts.values, fontsize=fontsize, rotation=45, ha='left')
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axes\_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\_api\deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axis.py", line 1790, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axis.py", line 1711, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (81).

2021-11-11 13:22:22,355 - ERROR    - Exception occurred while processing request: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (81).
Traceback (most recent call last):
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 100, in _handle_exceptions
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\dtale\views.py", line 3257, in build_missingno_chart
    figure = msno.bar(df)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\missingno\missingno.py", line 266, in bar
    ax3.set_xticklabels(nullity_counts.values, fontsize=fontsize, rotation=45, ha='left')
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axes\_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\_api\deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axis.py", line 1790, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "c:\users\amit jain\.conda\envs\tensorflow\lib\site-packages\matplotlib\axis.py", line 1711, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (0), usually from a call to set_ticks, does not match the number of ticklabels (81).